services:
  db:
    image: mysql
    container_name: dev_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root       
      MYSQL_DATABASE: contacts
    ports:
      - "3306:3306"              
    volumes:
      - db_data:/var/lib/mysql   

volumes:
  db_data:
